[project]
name = "quarto-engformat"
version = "1.0.0"
description = "Repository for engineering calculation formats for Typst"
readme = "README.md"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "polars",
    "ruff",
    "jupyter",
]

[tool.ruff]
# Add a custom file extension mapped to Python
extension = {qmd="markdown"}
