---
title: Some Calculation  # this is the title of the calculation document
format:
  engformat-typst:
    company: Some Company # the company name, displayed (in all caps) in the footer.
    proj_name: Some Project # The project name, displayed in the header.
    proj_number: Ryymmxxx  # the project number, displayed in the header.
    calc_no: Ryymmxxx_CAL001  # the calculation number, used in the header.
    calc_title: Some Project  # the calculation title, used in the header.
# provide a logo for the company (LHS of header)
# Note that using _ in the file names appears to give errors.
    logo_company: "logo-company.jpg" 

  # provide a list of revisions, in descedending order (e.g. add new revisions at the bottom)
    revisions:
    - rev_no: A
      rev_date: 24/04/2026
      rev_desc: Preliminary
      rev_prep: A. Engineer
      rev_check: B. Engineer
      rev_app: C. Engineer
    - rev_no: B
      rev_date: 25/04/2026
      rev_desc: More preliminary
      rev_prep: B. Engineer
      rev_check: B. Engineer
      rev_app: B. Engineer
    - rev_no: C
      rev_date: 26/04/2026
      rev_desc: Even More preliminary
      rev_prep: C. Engineer
      rev_check: C. Engineer
      rev_app: C. Engineer
    - rev_no: D
      rev_date: 27/04/2026
      rev_desc: Heaps More preliminary
      rev_prep: D. Engineer
      rev_check: D. Engineer
      rev_app: D. Engineer
---

# Document Purpose {#sec-intro}

This is a Quarto document template (`.qmd`) intended to be used to develop engineering calculations in the format of a typical engineering calculation pad. Now you too can use python in your calculation documents:

```{python}
print("Hello World!")
```

Also, it produces some of the nicest looking calculation documents that have ever caressed your eyes!

## Instructions
To use, install ``python`` (or ``R`` or whatever programming language you like!) and ``quarto`` and then run the following command to download the template:

```bash
quarto use template skane88/quarto-engformat/engformat_03
```

Now just edit in your favourite notebook editor: Jupyter (can use native ``.ipynb`` or use Jupytext to edit ``.qmd`` files), VSCode, RStudio, etc.

For quarto instructions see:

[Quarto Documentation](https://quarto.org/docs/get-started/hello/jupyter.html)

You can learn more about creating custom Typst templates here: 

[Custom Typst Templates](https://quarto.org/docs/output-formats/typst-custom.html)

:::{#tip-intro .callout-tip title="Introductions"}
For actual use, the introduction should be a _brief_ description of the calculation objective and scope and ideally include a picture.
:::

{{< pagebreak >}}

```{=typst}
#block(above: 2em, below: 2em)[
    #outline(
      title: [Table of Contents],
      depth: 2,
      indent: auto
    );
    ]
```

{{< pagebreak >}}

# Basis of Design

## Design Brief & Client Requirements

## Design Constraints and Battery Limits

##	Parameters

###	Geometry 

###	Material Properties 

##	Design Changes
##	Governing Standard and Regulations

The following table lists the primary standards and specifications and specifications followed for this project.

The following is a pipe-table. This is the simplest form of table with limited formatting options. It can be cross referenced (@tbl-specs-pipe), and can be given captions.

| Item | Reference | Year | Description |
|---------|----------|----------|----------|
| |AS 4100 | 2020|Steel Structures|
| | | | |
| | | | |

: Standards and Specifications {#tbl-specs-pipe}

The following is a list-table (@tbl-specs-list). This is a complex table type that allows more formatting options and the ability to merge cells. However, the table is quite difficult to write, so use should generally be limited.

::: {#tbl-specs-list .list-table aligns="l" tbl-colwidths="[10,25, 15, 50]" }
Standards and Specifications.

- - Item
  - Reference
  - Year
  - Description

- - []{colspan=4} Standards

- -
  - AS 4100
  - 2020
  - Steel Structures

- -
  -
  -
  -

- - []{colspan=4} Specifications

- -
  -
  -
  -

:::

It is also possible to directly incorporate `typst` blocks into the document for complete control over formatting.

{{< pagebreak >}}

# Work Records

The following design calculations have been relied upon in the preparation of this calculation:

| Doc Number | Title | Revision | Link / Path |
|---------|----------|----------|----------|
|R26xxx_CAL002|Structural Steel Design|A|[link](https://example.com)|
|R26xxx_CAL003|Foundation Design|A|[link](https://example.com)|

: Work Records {#tbl-work-records}

{{< pagebreak >}}

# Design Loading
This section describes the loads applied.

## Gravity Loads
Document gravity loads here.

### GSW Structural Self Weight
Structural self weight is applied as an acceleration in the model unless noted otherwise.

### GFM Flooring
Floor mesh self weight is assumed to be:

$mass = 50 \, \text{kg/m}^2$

$GFM = mass \times g_{acc} = 0.5 \, \text{kPa}$

:::{#tip-eqn .callout-tip title="Symbolic Maths"}
NOTE: Just because you can use pretty maths in Quarto doesn't mean you should. They take time and effort to type out properly. Prefer using simple python code blocks where possible. If you need to do symbolic maths, consider using ``sympy`` which can symbolically solve equations and output them for you.
:::

Flooring is applied as follows:

* A dummy load case of 1kPa is applied to all floor areas.
* The actual floor load is then applied as a load combination of 0.5 x the dummy case.

### GHR Handrails
Handrails are assumed to be 15kg/m.

$GHR = 15 \text{kg/m} \times g_{acc} = 1.5 \text{kN/m}$

### GME Mechanical Equipment
Break into multiple load cases if required.

## Live Loads

### QLL5 Standard Floor Live Load

### QME Mechanical Equipment Live Load
Break into multiple load cases if required.

## Load Combinations

### Ultimate Limit State (ULS) Load Combinations

### Serviceability Limit State (SLS) Load Combinations

### Fatigue and Design Life Combinations

{{< pagebreak >}}

# Analysis Model

The following figure shows the analysis model:

## Restraints, Releases & Offsets
The following restraints, releases and offsets have been used:

* All columns assumed to be pinned at base unless otherwise noted.
* All members assumed to be pinned at their ends unless otherwise noted.
* Members modelled at their centrelines unless otherwise noted.

## Analysis Method
The following analysis methods have been used:

* Non-linear static analysis.
* Linear buckling where required to determine effective lengths for members.


## Steel / Concrete Design Assumptions
The following steel and concrete design assumptions have been used:

* ...

{{< pagebreak >}}

# Summary

We have done some awesome calcs.

{{< pagebreak >}}

# Calculation

Copy this section as required.

## Example Calcs
Do some calculation here.

```{python}
from cycler import cycler
import numpy as np
import polars as pl
import matplotlib.pyplot as plt

a = 1
b = 2
a + b
```

And now plot a graph (see @fig-test), with the graph code hidden in a collapsed code cell:

```{python}
no_points = 101
jitter_scale = 0.2
x = np.linspace(0, 2 * np.pi, no_points)
y1 = np.sin(x) + (np.random.random(no_points) - 0.5) * jitter_scale
y2 = np.cos(x) + (np.random.random(no_points) - 0.5) * jitter_scale
y3 = np.sin(x * 2) + (np.random.random(no_points) - 0.5) * jitter_scale
y4 = np.cos(x * 2) + (np.random.random(no_points) - 0.5) * jitter_scale
y5 = np.sin(x * 3) + (np.random.random(no_points) - 0.5) * jitter_scale
y6 = np.cos(x * 3) + (np.random.random(no_points) - 0.5) * jitter_scale
```

```{python}
#| echo: FALSE
#| label: fig-test
#| fig-cap: Test Figure

PERSONAL_COLORS = cycler(
    color=[
        "#228c3d",
        "#808285",
        "#f3ab1d",
        "#9c1421",
        "#00a3d8",
        "#004270",
    ]
)

plt.gca().set_prop_cycle(PERSONAL_COLORS)
plt.plot(x, y1, label="y1")
plt.plot(x, y2, label="y2")
plt.plot(x, y3, label="y3")
plt.plot(x, y4, label="y4")
plt.plot(x, y5, label="y5")
plt.plot(x, y6, label="y6")
plt.legend()
plt.title("Test Figure")
```

:::{#tip-tipgraph .callout-tip title="Hidden code blocks"}
Use the ``#| echo: FALSE`` option to hide code blocks and minimise clutter.
:::

Woohoo!

And do some data processing with Polars (see @tbl-test):

```{python}
#| label: tbl-test
#| tbl-cap:
#|   "Test Data"

df = pl.DataFrame({"x": x, "y": y1, "z": y2})

pl.Config.set_tbl_hide_column_data_types(True)
pl.Config.set_float_precision(3)

df.head()
```


:::{#tip-tip .callout-tip title="Tip"}
This is an example of a callout "tip".
:::

:::{.callout-warning title="Warning"}
This is an example of a callout "warning".
:::

:::{.callout-important title="Important"}
This is an example of an "important" callout.
:::

Callouts can even be cross-referenced - see @tip-tip. So can sections - see @sec-intro.

{{< pagebreak >}}

# Appendix A

{{< pagebreak >}}

# Appendix B
